### ISSUE TITLE
heads-up: FTP files have moved to HTTP

### ISSUE THREAD

**Issue by stapelberg** [HDebeuf/balena-raspberry-pi4-omada-controller#1]
The new URL is https://rent-a-guru.de/ftp/omada-controller_3.2.1-1_all.deb

**Comment by HDebeuf** [comment]
@stapelberg  Thanks for the hint.
I was just wondering if omada-controller_3.2.1-1_all.deb is still available ?
The new url doesn't seem to have this version.

**Comment by stapelberg** [comment]
Is there any reason you can’t use omada-controller_3.2.10-3_all.deb instead?

**Comment by HDebeuf** [comment]
The Docker image has been upgraded and it seems to work perfectly on my side.
Thank you.
